### ISSUE TITLE
Not working on gnome 3.32

### ISSUE THREAD

**Issue by fthiery** [underdoeg/redmine_time_tracker-undef.ch#9]
Just tried to install this, but it won't work anymore:

```
juil. 10 09:01:19 flowtop gnome-shell[26798]: JS WARNING: [/home/fthiery/.local/share/gnome-shell/extensions/redmine_time_tracker@undef.ch/extension.js 453]: Too many arguments to method Clutter.Container.add_actor: expected 1, got 2
juil. 10 09:01:19 flowtop gnome-shell[26798]: Extension "redmine_time_tracker@undef.ch" had error: TypeError: this._construct is not a function
juil. 10 09:01:19 flowtop gnome-software[27055]: redmine_time_tracker_undef.ch has error: TypeError: this._construct is not a function
```

**Comment by underdoeg** [comment]
sorry, I dont use this extension anymore. though the fix might be easy?

Try changing line 453

from ```this.mainBox.add_actor(topPane, {expand: false});```
to ```this.mainBox.add_actor(topPane);```
